--- !Config
translator:
  # engine: nllb or google
  engine: "google"
  srcFolder: "./input"
  tgtFolder: "./output"

engines:
  nllb:
    model: "facebook/nllb-200-distilled-600M"
    srcLang: "eng_Latn"
    tgtLang: "spa_Latn"
    maxLength: 50
  google:
    projectId: "sub-translator-395803"
    serviceAccKeyPath: ""
    srcLang: "en"
    tgtLang: "es"
